### ISSUE TITLE
Version of ffmpeg is too old, last release should be available: 4.4.x

### ISSUE THREAD

**Issue by Soulou** [Scalingo/ffmpeg-buildpack#4]

**Comment by EtienneM** [comment]
Raising it to high as it has been a LONG time it as not been updated

Moreover an internal doc should be written on the process to release a new version. This process is probably downloading the FFMpeg binary and uploading it on our object storage.

**Comment by EtienneM** [comment]
Waiting for an answer here: https://scalingo.slack.com/archives/C016X4Z8P7E/p1646661528256059

> Hey team product! I notice we still maintain the buildpack ffmpeg (https://github.com/Scalingo/ffmpeg-buildpack). I think we should deprecate it in favor of the APT buildpack. What do you think about this? ffmpeg is available with a recent version in the official Ubuntu repository (https://launchpad.net/ubuntu/+source/ffmpeg). We already did that kind of things with Puppeteer (https://doc.scalingo.com/languages/nodejs/puppeteer#install-puppeteer-on-a-scalingo-application).

It would require we use multi-buildpack, with the apt buildpack having the following Aptfile:

```
Aptfile
```


And we need to define the env variable:

```
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/app/.apt/usr/lib/x86_64-linux-gnu/pulseaudio"
```

**Comment by EtienneM** [comment]
Answer:

> I agree, let's drop official support and tell people to use apt-buildpack. But documentation should be clear how to install ffmpeg.

Note that the ffmpeg buildpack also have support for ffprobe (https://github.com/Scalingo/ffmpeg-buildpack#need-of-ffprobe). We should also document how to install ffprobe with the apt buildpack.
